### ISSUE TITLE
Better array type support for params

### ISSUE THREAD

**Issue by theogravity** [Zooz/api-schema-builder#17]
I have the following definition:

```
        - in: query
          name: ids
          type: array
          uniqueItems: true
          collectionFormat: csv
          required: true
          minItems: 1
          items:
            type: string
          description: A comma-separated list of ids, as a string
```

The validator only seems to check that the parameter is present, but will not check if it is empty or if the number of items matches when it is present but no value is assigned.
